// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUvcry876oOiIb9LGuAkCsG2vsQV1dVXU',
    appId: '1:103109887432:web:b9ec7237a2dfda83256cfd',
    messagingSenderId: '103109887432',
    projectId: 'classmatescorner-d7a5a',
    authDomain: 'classmatescorner-d7a5a.firebaseapp.com',
    storageBucket: 'classmatescorner-d7a5a.appspot.com',
    measurementId: 'G-K1E109PZ7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAsdGEAFativAYJ78eZ-lQ1TatxjwL-1k',
    appId: '1:103109887432:android:7b042ce87f208021256cfd',
    messagingSenderId: '103109887432',
    projectId: 'classmatescorner-d7a5a',
    storageBucket: 'classmatescorner-d7a5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-y1qK2PkQwLG4Ky7Eh-rf5LP4Z0_8vKU',
    appId: '1:103109887432:ios:03eccf5ab5fc6865256cfd',
    messagingSenderId: '103109887432',
    projectId: 'classmatescorner-d7a5a',
    storageBucket: 'classmatescorner-d7a5a.appspot.com',
    iosBundleId: 'com.example.classmatescorner',
  );
}
